import { Department, Agent, Approval, Activity, LiveInsight, InvestigationStep } from '../types/nexus';

export const DEPARTMENTS: Department[] = [
  {
    id: 'payment-ops',
    name: 'Payment Operations',
    descriptor: 'Keep payments healthy.',
    iconName: 'CreditCard',
    status: 'Monitoring actively',
    priority: 'Investigate elevated evening payment failures',
    finding: 'Payment failures increased by 3.4× between 7 PM and 10 PM.',
    recommendedAction: 'Apply dynamic UPI routing to secondary gateway provider.',
    capabilities: [
      'Real-time payment monitoring',
      'Anomaly detection',
      'Gateway health analysis',
      'Root-cause investigation',
      'Incident escalation',
    ],
    agentIds: ['payment-sentinel', 'failure-investigator', 'payment-health-analyst', 'incident-coordinator'],
    metrics: [
      { label: 'Success Rate', value: '94.2%', change: '-3.1%', isPositive: false },
      { label: 'Avg Latency', value: '840ms', change: '+120ms', isPositive: false },
      { label: 'Volume (24h)', value: '₹48.2L', change: '+8.4%', isPositive: true },
      { label: 'Active Alerts', value: '2', change: 'Elevated', isPositive: false },
    ],
  },
  {
    id: 'finance-recon',
    name: 'Finance & Reconciliation',
    descriptor: 'Account for every rupee.',
    iconName: 'Scale',
    status: 'Auto-reconciling',
    priority: 'Resolve 32 pending settlement exceptions',
    finding: '32 reconciliation exceptions detected, including one ₹150 settlement mismatch.',
    recommendedAction: 'Auto-adjust verified ledger items and flag external fee gap.',
    capabilities: [
      'Transaction matching',
      'Settlement analysis',
      'Refund tracking',
      'Discrepancy detection',
      'Reconciliation workflows',
    ],
    agentIds: ['settlement-investigator', 'refund-tracker', 'financial-analyst', 'reconciliation-coordinator'],
    metrics: [
      { label: 'Matched Rate', value: '99.4%', change: '+0.2%', isPositive: true },
      { label: 'Exceptions', value: '32', change: '-8 vs yday', isPositive: true },
      { label: 'Pending Settl.', value: '₹14.8L', change: 'On schedule', isPositive: true },
      { label: 'Discrepancy Gap', value: '₹150', change: 'Actionable', isPositive: false },
    ],
  },
  {
    id: 'merchant-growth',
    name: 'Merchant Growth',
    descriptor: 'Find opportunities to grow.',
    iconName: 'TrendingUp',
    status: 'Forecasting active',
    priority: 'Targeted recovery campaign for dropped-off high-tier buyers',
    finding: 'Targeted re-engagement may recover approximately 12% potential revenue.',
    recommendedAction: 'Deploy VIP personalized incentive for repeat order recovery.',
    capabilities: [
      'Revenue forecasting',
      'Opportunity discovery',
      'Business analysis',
      'Campaign recommendations',
      'Growth strategy',
    ],
    agentIds: ['revenue-forecaster', 'opportunity-scout', 'business-analyst', 'campaign-strategist'],
    metrics: [
      { label: 'Projected Growth', value: '+18.4%', change: 'MoM', isPositive: true },
      { label: 'Revenue Deficit', value: '₹4.2L', change: 'Evening gap', isPositive: false },
      { label: 'Recoverable Opp.', value: '₹2.8L', change: 'Ready', isPositive: true },
      { label: 'Campaign ROI', value: '5.2x', change: 'Est.', isPositive: true },
    ],
  },
  {
    id: 'customer-intel',
    name: 'Customer Intelligence',
    descriptor: 'Understand customer behavior.',
    iconName: 'Users',
    status: 'Segmenting cohorts',
    priority: 'Address drop in high-value customer repurchase velocity',
    finding: 'High-value customer activity is down 32% compared with last month.',
    recommendedAction: 'Engage 1,420 affected customers with priority checkout link.',
    capabilities: [
      'Customer segmentation',
      'Churn prediction',
      'Customer behavior analysis',
      'Support intelligence',
      'Retention recommendations',
    ],
    agentIds: ['customer-segmenter', 'churn-predictor', 'customer-support-agent', 'retention-coordinator'],
    metrics: [
      { label: 'Cohort Retention', value: '71.2%', change: '-4.8%', isPositive: false },
      { label: 'At-Risk Cohort', value: '1,420', change: '+340', isPositive: false },
      { label: 'High-Value Pool', value: '4,890', change: 'Active', isPositive: true },
      { label: 'CSAT Index', value: '4.8/5', change: '+0.1', isPositive: true },
    ],
  },
  {
    id: 'biz-ops',
    name: 'Business Operations',
    descriptor: 'Run smoother every day.',
    iconName: 'Layers',
    status: 'Optimizing workflows',
    priority: 'Maintain sub-10 minute resolution times across merchant support',
    finding: 'Automated workflows reduced issue resolution time by 28%.',
    recommendedAction: 'Expand auto-triage rules to regional fulfillment alerts.',
    capabilities: [
      'Operational analytics',
      'Process optimization',
      'Compliance monitoring',
      'Proactive alerts',
      'Decision support',
    ],
    agentIds: ['operations-analyst', 'process-optimizer', 'compliance-monitor', 'decision-support-agent'],
    metrics: [
      { label: 'Avg Resolution', value: '9.4 min', change: '-28%', isPositive: true },
      { label: 'Automations Run', value: '1,840', change: '+14% wk', isPositive: true },
      { label: 'Compliance Score', value: '99.8%', change: 'All pass', isPositive: true },
      { label: 'Ops Health', value: 'Optimal', change: 'Steady', isPositive: true },
    ],
  },
];

export const AGENTS: Record<string, Agent> = {
  // Payment Operations
  'payment-sentinel': {
    id: 'payment-sentinel',
    name: 'Payment Sentinel',
    departmentId: 'payment-ops',
    departmentName: 'Payment Operations',
    subtitle: 'Real-time monitoring. Early detection. Always on.',
    status: 'Active',
    iconName: 'ShieldAlert',
    objective: 'Continuous transaction telemetry surveillance across all payment gateways and channels.',
    currentTask: 'Monitoring UPI failure spikes and gateway latency anomaly patterns.',
    dataSources: ['Paytm Gateway API', 'NPCI Switch Feed', 'HDFC Core Bridge', 'Merchant SDK Logs'],
    confidenceLevel: 98,
    lastUpdate: 'Just now',
    finding: 'Payment failures increased by 3.4× between 7 PM and 10 PM on UPI routes.',
    capabilities: ['Telemetry ingestion', 'Baseline deviation detection', 'Spike alarms', 'Traffic routing hints'],
  },
  'failure-investigator': {
    id: 'failure-investigator',
    name: 'Failure Investigator',
    departmentId: 'payment-ops',
    departmentName: 'Payment Operations',
    subtitle: 'Deep root-cause diagnostics down to error codes and bank switches.',
    status: 'Analyzing',
    iconName: 'Search',
    objective: 'Isolate root causes behind payment degradation and pinpoint bank-side timeouts.',
    currentTask: 'Deconstructing error responses for UPI transaction failures in the 7-10 PM window.',
    dataSources: ['NPCI Return Codes', 'Bank Host Responses', 'Network Traceroutes', 'User Device Telemetry'],
    confidenceLevel: 95,
    lastUpdate: '2 mins ago',
    finding: 'Bank gateway degradation detected at partner switch: TIMEOUT_U16.',
    capabilities: ['Error code taxonomy', 'Gateway comparative benchmarking', 'Timeout tracing', 'Correlation engine'],
  },
  'payment-health-analyst': {
    id: 'payment-health-analyst',
    name: 'Payment Health Analyst',
    departmentId: 'payment-ops',
    departmentName: 'Payment Operations',
    subtitle: 'Longitudinal payment conversion metrics and health scoring.',
    status: 'Monitoring',
    iconName: 'Activity',
    objective: 'Maintain rolling 30-day baseline conversion models by method, OS, and bank.',
    currentTask: 'Recalculating hourly conversion benchmarks for merchant checkout.',
    dataSources: ['Aggregated Transaction DB', 'Browser Fingerprints', 'Payment Method Registry'],
    confidenceLevel: 92,
    lastUpdate: '5 mins ago',
    capabilities: ['Baseline modeling', 'Conversion trend analytics', 'Method distribution', 'SLA monitoring'],
  },
  'incident-coordinator': {
    id: 'incident-coordinator',
    name: 'Incident Coordinator',
    departmentId: 'payment-ops',
    departmentName: 'Payment Operations',
    subtitle: 'Automated alert routing, merchant mitigation, and partner escalation.',
    status: 'Active',
    iconName: 'BellRing',
    objective: 'Orchestrate rapid mitigations and notify relevant ops stakeholders.',
    currentTask: 'Preparing failover routing recommendation for merchant approval.',
    dataSources: ['Incident Management Ledger', 'Slack Webhook', 'Merchant Notification Queue'],
    confidenceLevel: 97,
    lastUpdate: '1 min ago',
    capabilities: ['Automated escalation', 'Mitigation playbooks', 'Audit journaling', 'Merchant alerts'],
  },

  // Finance & Reconciliation
  'settlement-investigator': {
    id: 'settlement-investigator',
    name: 'Settlement Investigator',
    departmentId: 'finance-recon',
    departmentName: 'Finance & Reconciliation',
    subtitle: 'Precision transaction matching against bank settlement files.',
    status: 'Active',
    iconName: 'Receipt',
    objective: 'Reconcile 100% of order authorizations against gross nodal settlements.',
    currentTask: 'Auditing 32 pending settlement exceptions from yesterday’s cycle.',
    dataSources: ['Nodal Bank MIS Files', 'Merchant Order DB', 'GST Tax Logs', 'Fee Schedule Tables'],
    confidenceLevel: 99,
    lastUpdate: 'Just now',
    finding: '32 exceptions detected: 31 timing differences, 1 true ₹150 fee discrepancy.',
    capabilities: ['2-way & 3-way matching', 'Fee discrepancy identification', 'Settlement ledger verification'],
  },
  'refund-tracker': {
    id: 'refund-tracker',
    name: 'Refund Tracker',
    departmentId: 'finance-recon',
    departmentName: 'Finance & Reconciliation',
    subtitle: 'End-to-end refund lifecycle tracking and turnaround monitoring.',
    status: 'Monitoring',
    iconName: 'RotateCcw',
    objective: 'Ensure customer refunds credit within instant/2-hour SLA guidelines.',
    currentTask: 'Tracking 44 reverse transactions across ICICI and SBI endpoints.',
    dataSources: ['Refund Processing Queue', 'Customer Bank Confirmation Feed', 'Paytm Wallet Ledgers'],
    confidenceLevel: 96,
    lastUpdate: '8 mins ago',
    capabilities: ['Instant refund status', 'Reverse transaction tracking', 'Chargeback risk mitigation'],
  },
  'financial-analyst': {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    departmentId: 'finance-recon',
    departmentName: 'Finance & Reconciliation',
    subtitle: 'Cashflow analysis, MDR fee breakdown, and gross margin analytics.',
    status: 'Monitoring',
    iconName: 'DollarSign',
    objective: 'Provide daily net merchant receivable balances and MDR cost optimizations.',
    currentTask: 'Compiling weekly net settlement projection and interchange fee distribution.',
    dataSources: ['Settlement Statements', 'Interchange Tables', 'Merchant Payout Schedule'],
    confidenceLevel: 94,
    lastUpdate: '12 mins ago',
    capabilities: ['MDR fee auditing', 'Payout forecasting', 'Cashflow modeling', 'Tax reconciliation'],
  },
  'reconciliation-coordinator': {
    id: 'reconciliation-coordinator',
    name: 'Reconciliation Coordinator',
    departmentId: 'finance-recon',
    departmentName: 'Finance & Reconciliation',
    subtitle: 'Closing discrepancies and auto-posting journal balances.',
    status: 'Awaiting approval',
    iconName: 'CheckCircle2',
    objective: 'Coordinate exception waivers and journal entries with merchant accounts.',
    currentTask: 'Queued waiver recommendation for ₹150 fee anomaly awaiting merchant approval.',
    dataSources: ['Accounting Bridge API', 'Tally/Zoho Sync', 'Exception Log'],
    confidenceLevel: 98,
    lastUpdate: '4 mins ago',
    capabilities: ['Journal entry preparation', 'Exception workflow routing', 'ERP syncing'],
  },

  // Merchant Growth
  'revenue-forecaster': {
    id: 'revenue-forecaster',
    name: 'Revenue Forecaster',
    departmentId: 'merchant-growth',
    departmentName: 'Merchant Growth',
    subtitle: 'Predictive revenue run-rate and demand trajectory analysis.',
    status: 'Active',
    iconName: 'TrendingUp',
    objective: 'Forecast hourly, daily, and monthly GMV trends against seasonality and anomalies.',
    currentTask: 'Calculating revenue loss impact caused by evening payment degradation.',
    dataSources: ['Historical GMV Stream', 'Order Velocity Indices', 'Festival & Weekend Multipliers'],
    confidenceLevel: 96,
    lastUpdate: 'Just now',
    finding: 'Projected revenue growth is +18%, but evening failure created a ₹4.2L deficit.',
    capabilities: ['ARIMA/Time-series forecasting', 'Deficit attribution', 'Seasonal indexing', 'Run-rate projection'],
  },
  'opportunity-scout': {
    id: 'opportunity-scout',
    name: 'Opportunity Scout',
    departmentId: 'merchant-growth',
    departmentName: 'Merchant Growth',
    subtitle: 'Proactive detection of uncaptured revenue and customer re-orders.',
    status: 'Active',
    iconName: 'Compass',
    objective: 'Surface high-ROI interventions to lift repeat order conversion.',
    currentTask: 'Evaluating recovery value potential for recent failed checkout buyers.',
    dataSources: ['Cart Abandonment Events', 'Product Catalog Affinity', 'Price Elasticity Engine'],
    confidenceLevel: 93,
    lastUpdate: '3 mins ago',
    finding: 'Found ₹2.8L recoverable revenue through targeted high-tier cart recovery.',
    capabilities: ['Uncaptured demand detection', 'Upsell mapping', 'Affinity clustering'],
  },
  'business-analyst': {
    id: 'business-analyst',
    name: 'Business Analyst',
    departmentId: 'merchant-growth',
    departmentName: 'Merchant Growth',
    subtitle: 'Product category sales performance and average order value diagnostics.',
    status: 'Monitoring',
    iconName: 'BarChart3',
    objective: 'Highlight top-moving SKUs, basket sizing, and channel margin performance.',
    currentTask: 'Analyzing basket size distribution across D2C website vs marketplace orders.',
    dataSources: ['SKU Order Logs', 'Catalog Performance DB', 'Promo Code Utilizations'],
    confidenceLevel: 91,
    lastUpdate: '15 mins ago',
    capabilities: ['SKU diagnostics', 'Basket size optimization', 'Channel comparison'],
  },
  'campaign-strategist': {
    id: 'campaign-strategist',
    name: 'Campaign Strategist',
    departmentId: 'merchant-growth',
    departmentName: 'Merchant Growth',
    subtitle: 'Automated recovery and retention campaign design for merchant approval.',
    status: 'Awaiting approval',
    iconName: 'Sparkles',
    objective: 'Generate precision marketing recommendations backed by clear expected ROAS.',
    currentTask: 'Formulated Recovery Campaign for 1,420 inactive high-value customers.',
    dataSources: ['Customer Segment Profiles', 'WhatsApp/SMS Delivery Rates', 'Discount Incentive Engine'],
    confidenceLevel: 97,
    lastUpdate: 'Just now',
    finding: 'Targeted recovery campaign can recover 12% revenue (~₹2.8L) with 5.2x ROI.',
    capabilities: ['Campaign synthesis', 'Incentive budgeting', 'Copy drafting', 'Approval queue packaging'],
  },

  // Customer Intelligence
  'customer-segmenter': {
    id: 'customer-segmenter',
    name: 'Customer Segmenter',
    departmentId: 'customer-intel',
    departmentName: 'Customer Intelligence',
    subtitle: 'Dynamic RFM clustering and customer lifetime value tiering.',
    status: 'Active',
    iconName: 'Users',
    objective: 'Classify entire merchant customer base into actionable behavioral cohorts.',
    currentTask: 'Isolating 1,420 high-value customers who dropped off post-evening payment errors.',
    dataSources: ['Customer Order History', 'Repeat Cadence Engine', 'Customer LTV DB'],
    confidenceLevel: 96,
    lastUpdate: 'Just now',
    finding: 'High-value customer activity is down 32% compared with last month.',
    capabilities: ['RFM clustering', 'Cohort transitions', 'LTV tier segmentation', 'Drop-off analysis'],
  },
  'churn-predictor': {
    id: 'churn-predictor',
    name: 'Churn Predictor',
    departmentId: 'customer-intel',
    departmentName: 'Customer Intelligence',
    subtitle: 'Early warning signals before valuable customers lapse.',
    status: 'Active',
    iconName: 'UserMinus',
    objective: 'Score probability of churn within 14 days based on engagement velocity.',
    currentTask: 'Assessing churn acceleration on customers who experienced payment failures.',
    dataSources: ['Visit Frequency Logs', 'Payment Outcome Signals', 'Ticket Sentiment'],
    confidenceLevel: 94,
    lastUpdate: '2 mins ago',
    finding: 'Payment friction doubled 14-day churn probability for affected high-tier buyers.',
    capabilities: ['Churn risk scoring', 'Lapse trigger detection', 'Survival curve modeling'],
  },
  'customer-support-agent': {
    id: 'customer-support-agent',
    name: 'Customer Support Agent',
    departmentId: 'customer-intel',
    departmentName: 'Customer Intelligence',
    subtitle: 'Merchant customer inquiry intelligence and ticket sentiment synthesis.',
    status: 'Monitoring',
    iconName: 'MessageSquareHeart',
    objective: 'Detect spike in complaints regarding failed charges or refund delays.',
    currentTask: 'Synthesizing merchant inbound feedback regarding pending UPI debits.',
    dataSources: ['Support Ticket Feed', 'WhatsApp Bot Inquiries', 'App Store Review Feed'],
    confidenceLevel: 92,
    lastUpdate: '7 mins ago',
    capabilities: ['Inquiry clustering', 'Sentiment indexing', 'Complaint early warning'],
  },
  'retention-coordinator': {
    id: 'retention-coordinator',
    name: 'Retention Coordinator',
    departmentId: 'customer-intel',
    departmentName: 'Customer Intelligence',
    subtitle: 'Tailored VIP loyalty perks and automated high-touch reach outs.',
    status: 'Monitoring',
    iconName: 'HeartHandshake',
    objective: 'Orchestrate delight touchpoints for VIP and at-risk enterprise buyers.',
    currentTask: 'Syncing VIP cohort list with Campaign Strategist recovery package.',
    dataSources: ['Loyalty Tier Records', 'Personalized Voucher Pool', 'CRM Sync Log'],
    confidenceLevel: 95,
    lastUpdate: '10 mins ago',
    capabilities: ['Loyalty intervention', 'VIP whitelist routing', 'Retention playbook triggers'],
  },

  // Business Operations
  'operations-analyst': {
    id: 'operations-analyst',
    name: 'Operations Analyst',
    departmentId: 'biz-ops',
    departmentName: 'Business Operations',
    subtitle: 'Cross-functional operational throughput and order fulfillment surveillance.',
    status: 'Active',
    iconName: 'Gauge',
    objective: 'Track end-to-end merchant operational throughput from payment to shipping.',
    currentTask: 'Evaluating order processing bottleneck between checkout and fulfillment.',
    dataSources: ['WMS/Fulfillment Logs', 'Courier Integration Feeds', 'Inventory Ledger'],
    confidenceLevel: 93,
    lastUpdate: '3 mins ago',
    finding: 'Average order processing time decreased to 14 mins across warehouse zones.',
    capabilities: ['Cycle time analytics', 'Bottleneck detection', 'Throughput monitoring'],
  },
  'process-optimizer': {
    id: 'process-optimizer',
    name: 'Process Optimizer',
    departmentId: 'biz-ops',
    departmentName: 'Business Operations',
    subtitle: 'Autonomous workflow streamlining and operational delay reduction.',
    status: 'Active',
    iconName: 'Cpu',
    objective: 'Continually eliminate human latency in routine merchant operational workflows.',
    currentTask: 'Comparing before AI vs after AI resolution metrics for dispute triage.',
    dataSources: ['Workflow Audit Trail', 'Automation Engine Stats', 'Merchant SLA Metrics'],
    confidenceLevel: 97,
    lastUpdate: 'Just now',
    finding: 'Automated workflows reduced issue resolution time by 28% (down to 9.4 mins).',
    capabilities: ['Workflow optimization', 'SLA acceleration', 'Automation efficiency tracking'],
  },
  'compliance-monitor': {
    id: 'compliance-monitor',
    name: 'Compliance Monitor',
    departmentId: 'biz-ops',
    departmentName: 'Business Operations',
    subtitle: 'RBI, GST, and PCI-DSS merchant compliance verification.',
    status: 'Monitoring',
    iconName: 'ShieldCheck',
    objective: 'Ensure all transactional data, invoice archives, and token vaults meet RBI guidelines.',
    currentTask: 'Verifying card tokenization compliance and GST tax invoice hash integrity.',
    dataSources: ['Token Vault Logs', 'GST e-Invoice Registry', 'PCI-DSS Audit Trail'],
    confidenceLevel: 99,
    lastUpdate: '20 mins ago',
    capabilities: ['Regulatory checks', 'Tokenization audit', 'GST reconciliation sync'],
  },
  'decision-support-agent': {
    id: 'decision-support-agent',
    name: 'Decision Support Agent',
    departmentId: 'biz-ops',
    departmentName: 'Business Operations',
    subtitle: 'Executive synthesis and multi-department operational recommendations.',
    status: 'Active',
    iconName: 'GitMerge',
    objective: 'Synthesize cross-department intelligence into daily merchant executive briefings.',
    currentTask: 'Aggregating daily ops summary for store owner briefing.',
    dataSources: ['All Department Data Streams', 'Executive KPI Goals', 'Merchant Preference Rules'],
    confidenceLevel: 95,
    lastUpdate: '6 mins ago',
    capabilities: ['Executive briefing', 'Scenario modeling', 'Strategic decision framing'],
  },
};

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'appr-1',
    title: 'Recovery Campaign for Inactive High-Value Customers',
    recommendedBy: 'Campaign Strategist',
    agentId: 'campaign-strategist',
    department: 'Merchant Growth',
    audience: 'Inactive high-value customers (1,420 merchants & shoppers)',
    objective: 'Encourage repeat purchases following evening payment friction',
    expectedOutcome: 'Recover approx. ₹2.8L revenue (12% of lost GMV) with 5.2x estimated ROAS',
    budget: '₹25,000',
    duration: '7 days',
    channel: 'WhatsApp & App Push',
    status: 'Awaiting merchant approval',
    evidence: [
      '1,420 high-value customers encountered UPI failure between 7 PM - 10 PM',
      'Historical repeat rate drops by 41% if no recovery touchpoint occurs within 48h',
      'Segment has an average historical order value of ₹3,450',
      'A ₹250 instant cashback voucher yields a 24.6% redemption rate in prior test cohorts',
    ],
    createdAt: '12 mins ago',
    auditTrail: [
      { timestamp: '22:45', action: 'Opportunity surfaced by Opportunity Scout', actor: 'Opportunity Scout' },
      { timestamp: '22:48', action: 'Campaign draft assembled with ₹25k budget', actor: 'Campaign Strategist' },
      { timestamp: '22:50', action: 'Queued in Nexus Control Layer awaiting merchant sign-off', actor: 'System' },
    ],
  },
  {
    id: 'appr-2',
    title: 'Automated UPI Fallback Routing Adjustment',
    recommendedBy: 'Payment Sentinel',
    agentId: 'payment-sentinel',
    department: 'Payment Operations',
    audience: 'All UPI Intent & Collect transactions',
    objective: 'Route 65% of traffic through secondary tier-1 bank gateway to bypass current degradation',
    expectedOutcome: 'Restore UPI success rate from 88.2% back to 96.5% within 3 minutes',
    budget: '₹0 (Zero extra fee)',
    duration: 'Active until switch recovery',
    channel: 'Gateway Switch Engine',
    status: 'Awaiting merchant approval',
    evidence: [
      'Primary bank switch reporting 14.8% timeout spike (code: TIMEOUT_U16)',
      'Secondary gateway benchmarked at 98.4% success with 420ms latency',
      'No disruption to end-user payment handle or experience',
    ],
    createdAt: '25 mins ago',
    auditTrail: [
      { timestamp: '22:30', action: 'Anomaly flagged by Payment Sentinel', actor: 'Payment Sentinel' },
      { timestamp: '22:34', action: 'Root cause confirmed by Failure Investigator', actor: 'Failure Investigator' },
      { timestamp: '22:35', action: 'Failover policy prepared for merchant confirmation', actor: 'Payment Sentinel' },
    ],
  },
  {
    id: 'appr-3',
    title: 'Reconciliation Waiver for ₹150 Fee Discrepancy',
    recommendedBy: 'Settlement Investigator',
    agentId: 'settlement-investigator',
    department: 'Finance & Reconciliation',
    audience: 'Nodal Settlement Batch #84920',
    objective: 'Auto-adjust unallocated ₹150 interchange rounding discrepancy into merchant fee waiver ledger',
    expectedOutcome: 'Clear ledger blockage and enable release of remaining ₹14.8L payout today',
    budget: '₹150',
    duration: 'Immediate',
    channel: 'ERP Journal Sync',
    status: 'Awaiting merchant approval',
    evidence: [
      'Discrepancy caused by 0.01% GST fractional roundoff in bank nodal file',
      'Value is within 0.001% of total batch value (₹14,82,400)',
      'Auditor guidelines permit automated micro-discrepancy balancing',
    ],
    createdAt: '40 mins ago',
    auditTrail: [
      { timestamp: '22:15', action: 'Exception identified in batch #84920', actor: 'Settlement Investigator' },
      { timestamp: '22:20', action: 'Tax integrity validated by Compliance Monitor', actor: 'Compliance Monitor' },
      { timestamp: '22:22', action: 'Discrepancy waiver queued for merchant review', actor: 'Settlement Investigator' },
    ],
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    timestamp: '23:11:42',
    agent: 'Campaign Strategist',
    agentId: 'campaign-strategist',
    department: 'Merchant Growth',
    departmentId: 'merchant-growth',
    event: 'Drafted targeted re-engagement campaign for 1,420 inactive high-value customers.',
    status: 'Action Required',
    details: 'Awaiting merchant approval in Control Layer with ₹25k budget allocation.',
  },
  {
    id: 'act-2',
    timestamp: '23:09:15',
    agent: 'Opportunity Scout',
    agentId: 'opportunity-scout',
    department: 'Merchant Growth',
    departmentId: 'merchant-growth',
    event: 'Identified ₹2.8L recoverable revenue opportunity from evening drop-offs.',
    status: 'Info',
    details: 'Modeled customer willingness to re-order using 48-hour incentive window.',
  },
  {
    id: 'act-3',
    timestamp: '23:06:50',
    agent: 'Churn Predictor',
    agentId: 'churn-predictor',
    department: 'Customer Intelligence',
    departmentId: 'customer-intel',
    event: 'Flagged 38% increase in 14-day churn probability for failed payment cohort.',
    status: 'Warning',
    details: 'Alerted Customer Segmenter and Retention Coordinator to prioritize cohort.',
  },
  {
    id: 'act-4',
    timestamp: '23:04:18',
    agent: 'Customer Segmenter',
    agentId: 'customer-segmenter',
    department: 'Customer Intelligence',
    departmentId: 'customer-intel',
    event: 'Isolated 1,420 high-value customers affected by recent evening checkout friction.',
    status: 'Info',
    details: 'Segment average order value is ₹3,450; 82% are repeat buyers.',
  },
  {
    id: 'act-5',
    timestamp: '23:01:05',
    agent: 'Revenue Forecaster',
    agentId: 'revenue-forecaster',
    department: 'Merchant Growth',
    departmentId: 'merchant-growth',
    event: 'Calculated ₹4.2L revenue deficit compared to expected seasonal run-rate.',
    status: 'Warning',
    details: 'Deficit attributed to UPI checkout failure between 7 PM and 10 PM.',
  },
  {
    id: 'act-6',
    timestamp: '22:58:30',
    agent: 'Failure Investigator',
    agentId: 'failure-investigator',
    department: 'Payment Operations',
    departmentId: 'payment-ops',
    event: 'Identified partner gateway degradation (TIMEOUT_U16) as root cause of failure spike.',
    status: 'Warning',
    details: 'Notified Payment Sentinel and Incident Coordinator to initiate failover.',
  },
  {
    id: 'act-7',
    timestamp: '22:55:12',
    agent: 'Payment Sentinel',
    agentId: 'payment-sentinel',
    department: 'Payment Operations',
    departmentId: 'payment-ops',
    event: 'Detected 3.4x spike in payment failures between 7 PM and 10 PM.',
    status: 'Warning',
    details: 'Telemetry baseline deviation of 6.8% detected on UPI intent route.',
  },
  {
    id: 'act-8',
    timestamp: '22:42:00',
    agent: 'Settlement Investigator',
    agentId: 'settlement-investigator',
    department: 'Finance & Reconciliation',
    departmentId: 'finance-recon',
    event: 'Reconciled 14,280 transactions against bank MIS files; isolated ₹150 discrepancy.',
    status: 'Info',
    details: '99.4% matched cleanly. One rounding fee exception flagged for review.',
  },
  {
    id: 'act-9',
    timestamp: '22:30:10',
    agent: 'Process Optimizer',
    agentId: 'process-optimizer',
    department: 'Business Operations',
    departmentId: 'biz-ops',
    event: 'Autonomous dispute workflow reduced merchant resolution time by 28% to 9.4 mins.',
    status: 'Success',
    details: 'Self-healing API retry solved 84 pending webhook deliveries.',
  },
];

export const LIVE_INSIGHTS: LiveInsight[] = [
  {
    id: 'ins-1',
    title: 'Payment failures increased by 3.4× during evening peak hours (7–10 PM).',
    departmentId: 'payment-ops',
    departmentName: 'Payment Operations',
    agentId: 'payment-sentinel',
    agentName: 'Payment Sentinel',
    severity: 'warning',
    metric: 'UPI failures +3.4x',
  },
  {
    id: 'ins-2',
    title: '32 settlement exceptions detected, including one ₹150 settlement mismatch.',
    departmentId: 'finance-recon',
    departmentName: 'Finance & Reconciliation',
    agentId: 'settlement-investigator',
    agentName: 'Settlement Investigator',
    severity: 'info',
    metric: '32 exceptions',
  },
  {
    id: 'ins-3',
    title: 'High-value customer activity declined by 32% compared with last month.',
    departmentId: 'customer-intel',
    departmentName: 'Customer Intelligence',
    agentId: 'customer-segmenter',
    agentName: 'Customer Segmenter',
    severity: 'warning',
    metric: 'Activity -32%',
  },
  {
    id: 'ins-4',
    title: 'A targeted recovery campaign could recover approximately ₹2.8L (12% GMV).',
    departmentId: 'merchant-growth',
    departmentName: 'Merchant Growth',
    agentId: 'campaign-strategist',
    agentName: 'Campaign Strategist',
    severity: 'opportunity',
    metric: '+₹2.8L recoverable',
  },
  {
    id: 'ins-5',
    title: 'Operational resolution time improved by 28% this week, down to 9.4 minutes.',
    departmentId: 'biz-ops',
    departmentName: 'Business Operations',
    agentId: 'process-optimizer',
    agentName: 'Process Optimizer',
    severity: 'success',
    metric: '-28% resolution time',
  },
];

export const INVESTIGATION_STEPS: InvestigationStep[] = [
  {
    stepNumber: 1,
    agentId: 'payment-sentinel',
    agentName: 'Payment Sentinel',
    department: 'Payment Operations',
    task: 'Auditing 24-hour transaction telemetry across all payment methods & gateways...',
    output: 'UPI failures increased by 3.4× between 7 PM and 10 PM. Peak failure rate hit 11.8%.',
    metric: '88.2% Success Rate',
    confidence: 99,
  },
  {
    stepNumber: 2,
    agentId: 'revenue-forecaster',
    agentName: 'Revenue Forecaster',
    department: 'Merchant Growth',
    task: 'Calculating GMV impact against expected evening baseline velocity...',
    output: 'Estimated revenue deficit of ₹4.2L directly correlated with evening payment failure window.',
    metric: '₹4.2L Revenue Gap',
    confidence: 96,
  },
  {
    stepNumber: 3,
    agentId: 'customer-segmenter',
    agentName: 'Customer Segmenter',
    department: 'Customer Intelligence',
    task: 'Cross-referencing failed transaction IDs with customer LTV records...',
    output: '1,420 high-value customers affected. 82% of these users represent repeat brand buyers.',
    metric: '1,420 High-Value Users',
    confidence: 97,
  },
  {
    stepNumber: 4,
    agentId: 'churn-predictor',
    agentName: 'Churn Predictor',
    department: 'Customer Intelligence',
    task: 'Modeling customer disengagement probability over next 14 days...',
    output: 'High risk of customer inactivity detected. Churn probability escalated by 38% for impacted buyers.',
    metric: '38% Churn Risk Surge',
    confidence: 94,
  },
  {
    stepNumber: 5,
    agentId: 'opportunity-scout',
    agentName: 'Opportunity Scout',
    department: 'Merchant Growth',
    task: 'Evaluating recovery value from proactive VIP re-engagement touchpoint...',
    output: 'Potential recovery opportunity identified: ₹2.8L in repeat GMV through personalized incentive.',
    metric: '₹2.8L Recovery Upside',
    confidence: 95,
  },
  {
    stepNumber: 6,
    agentId: 'campaign-strategist',
    agentName: 'Campaign Strategist',
    department: 'Merchant Growth',
    task: 'Synthesizing audience, copy, channels, and voucher budget for merchant approval...',
    output: 'Recovery campaign prepared with 5.2x projected ROAS. Ready for merchant authorization.',
    metric: 'Ready for Approval',
    confidence: 98,
  },
];

// Rich Chart Datasets
export const PAYMENT_SUCCESS_HOURLY = [
  { time: '00:00', successRate: 98.2, failures: 12 },
  { time: '02:00', successRate: 98.9, failures: 6 },
  { time: '04:00', successRate: 99.1, failures: 3 },
  { time: '06:00', successRate: 98.4, failures: 18 },
  { time: '08:00', successRate: 97.6, failures: 45 },
  { time: '10:00', successRate: 96.8, failures: 89 },
  { time: '12:00', successRate: 96.2, failures: 110 },
  { time: '14:00', successRate: 95.8, failures: 98 },
  { time: '16:00', successRate: 96.4, failures: 104 },
  { time: '18:00', successRate: 94.1, failures: 186 },
  { time: '19:00', successRate: 89.2, failures: 342 },
  { time: '20:00', successRate: 87.8, failures: 410 },
  { time: '21:00', successRate: 88.5, failures: 388 },
  { time: '22:00', successRate: 92.4, failures: 215 },
  { time: '23:00', successRate: 96.5, failures: 74 },
];

export const PAYMENT_METHOD_BREAKDOWN = [
  { method: 'UPI Intent / QR', percentage: 68, count: 18400, color: '#0066FF' },
  { method: 'Credit / Debit Cards', percentage: 18, count: 4860, color: '#10245C' },
  { method: 'Netbanking', percentage: 9, count: 2430, color: '#7C5CFC' },
  { method: 'Paytm Wallet & Postpaid', percentage: 5, count: 1350, color: '#16B981' },
];

export const GATEWAY_HEALTH_DATA = [
  { gateway: 'Paytm PG Engine', successRate: 99.2, latency: '280ms', status: 'Healthy' },
  { gateway: 'HDFC Bank Switch', successRate: 98.4, latency: '420ms', status: 'Healthy' },
  { gateway: 'Axis Bank Switch', successRate: 97.9, latency: '490ms', status: 'Healthy' },
  { gateway: 'SBI Bank Switch (UPI)', successRate: 88.2, latency: '1,420ms', status: 'Degraded' },
];

export const REVENUE_FORECAST_DATA = [
  { day: 'Mon', actual: 6.8, forecast: 6.5, upper: 7.1, lower: 6.0 },
  { day: 'Tue', actual: 7.2, forecast: 7.0, upper: 7.6, lower: 6.4 },
  { day: 'Wed', actual: 6.9, forecast: 7.3, upper: 7.9, lower: 6.7 },
  { day: 'Thu', actual: 7.8, forecast: 7.5, upper: 8.2, lower: 6.9 },
  { day: 'Fri', actual: 6.2, forecast: 8.4, upper: 9.1, lower: 7.8 }, // Deficit
  { day: 'Sat (Proj)', actual: null, forecast: 9.6, upper: 10.4, lower: 8.8 },
  { day: 'Sun (Proj)', actual: null, forecast: 10.2, upper: 11.2, lower: 9.3 },
];

export const CUSTOMER_SEGMENTS = [
  { name: 'High-Value VIPs', count: 4890, percentage: 28, aov: '₹3,450', color: '#0066FF' },
  { name: 'Active Repeat Buyers', count: 6120, percentage: 35, aov: '₹1,620', color: '#10245C' },
  { name: 'At-Risk Cohort', count: 3840, percentage: 22, aov: '₹1,840', color: '#F59E0B' },
  { name: 'Inactive / Lapsed', count: 2620, percentage: 15, aov: '₹1,210', color: '#EF4444' },
];

export const OPS_EFFICIENCY_DATA = [
  { metric: 'Payment Incident Triage', beforeAI: '42 mins', afterAI: '4.8 mins', improvement: '88%' },
  { metric: 'Dispute Reconciliation', beforeAI: '65 mins', afterAI: '9.4 mins', improvement: '85%' },
  { metric: 'VIP Segment Cart Recovery', beforeAI: '24 hours', afterAI: '12 mins', improvement: '99%' },
  { metric: 'Daily Financial Settlement Audit', beforeAI: '120 mins', afterAI: '8.2 mins', improvement: '93%' },
];
